# 通过配置文件，只需一行命令 docker-compose up 替代构建及运行容器的所有命令
# 启动命令 docker-compose up --build
# up: 创建并启动容器
# --build: 每次启动容器前构建镜像

# build: 从当前路径构建镜像
version: "3"
services:
  simple:
    build:
      context: .
      dockerfile: simple.Dockerfile
    ports:
      - 4000:80
  route:
    build:
      context: .
      dockerfile: router.Dockerfile
    ports:
      - 3000:80
  oss:
    build:
      context: .
      dockerfile: oss.Dockerfile
      args:
        # 此处默认从宿主机(host)环境变量中传参，在宿主机中需要提前配置 ACCESS_KEY_ID/ACCESS_KEY_SECRET 环境变量
        - ACCESS_KEY_ID
        - ACCESS_KEY_SECRET
        - ENDPOINT=oss-cn-hangzhou.aliyuncs.com
    ports:
      - 8000:80